# Generated by Django 5.1.7 on 2025-03-28 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EMQXDevice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        help_text="Unique identifier for the EMQX client",
                        max_length=255,
                        unique=True,
                        verbose_name="EMQX Client ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether the device is active",
                        verbose_name="Is active",
                    ),
                ),
                (
                    "last_connected_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last successful connection",
                        null=True,
                        verbose_name="Last connected at",
                    ),
                ),
                (
                    "last_status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("error", "Error"),
                        ],
                        default="offline",
                        help_text="Last known status of the device",
                        max_length=20,
                        verbose_name="Last known status",
                    ),
                ),
                (
                    "subscribed_topics",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of topics the device subscribes to",
                        verbose_name="Subscribed Topics",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Last known IP address of the device",
                        null=True,
                        verbose_name="Last known IP address",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emqx_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        blank=True,
                        help_text="Optional MQTT topic to publish this message to. Leave blank for non-MQTT messages.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional short title for the message, suitable for UI display.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Optional longer body content of the message.",
                        null=True,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        help_text="Optional structured payload (e.g., for app actions or push notifications).",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the message was created.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional user who created or sent the message.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the notification was created or delivered.",
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the user acknowledged or read the notification.",
                        null=True,
                    ),
                ),
                (
                    "is_acknowledged",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the user has acknowledged the notification.",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="The message this notification is based on.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="django_emqx.message",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="The user who should receive this notification.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
